"""Frozen ASR backend — model / device / precision are hard-coded here.

Workspace MUST go through ``load()``, ``generate()`` and ``to_storage_view()``
helpers only. The Phase 3 static guard rejects any direct
``ctranslate2``/``transformers`` import in ``workspace/`` (see
``docs/PHASE3-PLAN.md §1.2``). Do not edit this file once Phase 3 starts.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

import ctranslate2
from ctranslate2.converters import TransformersConverter
from transformers import WhisperProcessor

log = logging.getLogger(__name__)

_MODEL_NAME = "openai/whisper-large-v3-turbo"
_MODEL_CACHE_PATH = (
    Path(__file__).resolve().parents[1] / ".cache" / "ct2_models" / "whisper-large-v3-turbo"
)
_DEVICE = "cuda"
_COMPUTE_TYPE = "float16"

_model: ctranslate2.models.Whisper | None = None
_processor: WhisperProcessor | None = None


def _ensure_ct2_cache() -> Path:
    """Convert HF weights to CT2 once and cache them."""
    if (_MODEL_CACHE_PATH / "model.bin").is_file():
        return _MODEL_CACHE_PATH

    log.warning(
        "CT2 cache missing — converting %s to %s (one-time, slow)",
        _MODEL_NAME,
        _MODEL_CACHE_PATH,
    )
    _MODEL_CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    converter = TransformersConverter(_MODEL_NAME, copy_files=["tokenizer.json"])
    converter.convert(
        output_dir=str(_MODEL_CACHE_PATH),
        quantization=_COMPUTE_TYPE,
        force=False,
    )
    return _MODEL_CACHE_PATH


def load() -> tuple[ctranslate2.models.Whisper, WhisperProcessor]:
    """Return the cached (model, processor) — both globals on first call."""
    global _model, _processor
    if _model is None or _processor is None:
        cache_dir = _ensure_ct2_cache()
        _processor = WhisperProcessor.from_pretrained(_MODEL_NAME)
        _model = ctranslate2.models.Whisper(
            str(cache_dir),
            device=_DEVICE,
            compute_type=_COMPUTE_TYPE,
        )
    return _model, _processor


def generate(features: Any, prompts: Any, **decoding_kwargs: Any) -> Any:
    """Pass-through to ``ctranslate2.models.Whisper.generate``.

    Decoding kwargs are open for workspace to evolve (beam_size, temperature,
    length_penalty, repetition_penalty, sampling_*, return_no_speech_prob, …).
    """
    model, _ = load()
    return model.generate(features, prompts, **decoding_kwargs)


def to_storage_view(np_array: Any) -> ctranslate2.StorageView:
    """numpy array → CT2 StorageView so workspace doesn't import ctranslate2."""
    return ctranslate2.StorageView.from_array(np_array)
